name: Lint, Build & Test on Linux

on: push

jobs:
  linux:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:5.5-latest
    steps:
      - uses: fwal/setup-swift@v1
      - uses: actions/checkout@v3
      - name: Lint
        run: swiftlint lint --reporter github-actions-logging --strict
      - name: Build
        run: swift build
      - name: Test
        run: swift test
